apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic1
spec:
  selector:
    matchLabels:
      app: petclinic1
  replicas: 1 
  template: 
    metadata:
      labels:
        app: petclinic1
    spec:
      containers:
      - name: petclinic1
        image: anuj730/jpipeline_demo:angular-build-4502
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic1
spec:
  type: LoadBalancer
  selector:
    app: petclinic1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

